# Generated by Django 3.1.3 on 2020-12-24 08:30

from django.db import migrations


def load_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    ExpenseType = apps.get_model('budget', 'ExpenseType')
    names = [
        'rent',
        'groceries',
        'eating out',
        'bills',
        'travel',
        'load payments'
    ]
    for name in names:
        expense_type = ExpenseType(name=name)
        expense_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
