# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-07 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_quiz_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.TextField(max_length=40),
        ),
    ]
