# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-07 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_auto_20201107_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
